// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxfaltxorosemngtxibu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54ZmFsdHhvcm9zZW1uZ3R4aWJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2OTU4ODEsImV4cCI6MjA2NjI3MTg4MX0.9PkUXlOkGjgYf4-lR1hTbnzMk9PaA8hhn7z0aDvASgc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);